name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install cloudscraper beautifulsoup4

      - name: Run script
        run: |
          python script.py

      - name: Copy file to GitHub Pages directory
        run: |
          mkdir -p docs
          cp data.txt docs/
